# Generated by Django 2.2.2 on 2019-06-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='rank',
            field=models.CharField(max_length=10),
        ),
    ]
