# Generated by Django 2.2.2 on 2019-06-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20190605_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='programhighlight',
            name='employed',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
