# Generated by Django 2.2.2 on 2019-06-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_programhighlight_employed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programhighlight',
            name='scholarship',
            field=models.CharField(max_length=3),
        ),
    ]
