# Generated by Django 2.2.2 on 2019-06-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_auto_20190605_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programhighlight',
            name='Intl_stud',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='programhighlight',
            name='avg_stud_age',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='programhighlight',
            name='avg_work_exp',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='programhighlight',
            name='class_size',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='programhighlight',
            name='scholarship',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='programhighlight',
            name='women_stud',
            field=models.CharField(max_length=6),
        ),
    ]
