# Generated by Django 2.2.2 on 2019-06-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_auto_20190605_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='city',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='university',
            name='link_to_program',
            field=models.URLField(max_length=150),
        ),
        migrations.AlterField(
            model_name='university',
            name='location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='university',
            name='rank',
            field=models.CharField(max_length=15),
        ),
    ]
