# Generated by Django 2.2.2 on 2019-06-06 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_auto_20190605_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programhighlight',
            old_name='link_to_program',
            new_name='name',
        ),
    ]
