# Generated by Django 2.2.2 on 2019-06-06 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_auto_20190606_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programhighlight',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='university.University'),
        ),
    ]
