# Generated by Django 2.2.2 on 2019-06-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_auto_20190606_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programhighlight',
            name='Intl_stud',
        ),
        migrations.AddField(
            model_name='programhighlight',
            name='intl_stud',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='programhighlight',
            name='accreditations',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='programhighlight',
            name='avg_salary',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='programhighlight',
            name='avg_stud_age',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='programhighlight',
            name='avg_work_exp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='programhighlight',
            name='class_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='programhighlight',
            name='employed',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='programhighlight',
            name='scholarship',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='programhighlight',
            name='start_month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='programhighlight',
            name='women_stud',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
