# Generated by Django 2.2.2 on 2019-06-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_auto_20190606_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programhighlight',
            old_name='avg_stud_age',
            new_name='avg_student_age',
        ),
        migrations.RenameField(
            model_name='programhighlight',
            old_name='avg_work_exp',
            new_name='avg_work_experience',
        ),
        migrations.RenameField(
            model_name='programhighlight',
            old_name='intl_stud',
            new_name='intl_students',
        ),
        migrations.RenameField(
            model_name='programhighlight',
            old_name='women_stud',
            new_name='women_students',
        ),
    ]
